Resources:
  MusicDistributionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.musicDistribution}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        -
          Key: 'CostCenter'
          Value: 'Music Distribution'
  PiecesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.pieces}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        -
          Key: 'CostCenter'
          Value: 'Music Distribution'
